"""T0.8 -- Emit a drop-in tablenotes snippet for table_439.tex.

The 439 master table compares a 3-seed LACE band against single-seed baselines. That
asymmetry is invisible in the table as laid out and a reviewer will find it. This writes a
`tablenotes` snippet to PASTE into phase4/table_439.tex and table_439_mdpi.tex. It does not
edit those files -- nothing in ablation/ writes outside ablation/.

Usage:
    .venv/bin/python -m boxinst_commonality_tcd_04.ablation.scripts.t08_table_notes
"""
import argparse
import json
import os

from ..lib import io

SNIPPET = r"""% ---------------------------------------------------------------------------
% Drop-in tablenotes for table_439.tex / table_439_mdpi.tex.
% Generated by boxinst_commonality_tcd_04/ablation/scripts/t08_table_notes.py
% Paste inside the existing \begin{tablenotes} ... \end{tablenotes} block.
% ---------------------------------------------------------------------------
\item[\dag] Seed coverage is not uniform across rows. LACE is a 3-seed band
  (seeds 0--2, $\pm$ is the sample standard deviation, $\mathrm{ddof}=1$);
  the fine-tuned DetecTree2 and SAM-3 box-prompt rows are \emph{single runs}
  (seed 0) and carry no variance estimate. Differences smaller than the LACE
  band should not be read as separating those rows.
\item[\ddag] All $\pm$ values in this table use the sample standard deviation
  ($\mathrm{ddof}=1$). Bands quoted from other parts of this project are not
  all computed this way -- the 16\,px 5-seed band recorded in
  \texttt{mps\_multiseed/README.md} as $0.4917 \pm 0.0231$ is a population
  standard deviation ($\mathrm{ddof}=0$); the same seeds give $\pm 0.0259$
  under the convention used here.
"""


def main():
    ap_ = argparse.ArgumentParser()
    ap_.add_argument("--out", default=os.path.join(io.RESULTS, "table_439_notes.tex"))
    a = ap_.parse_args()
    open(a.out, "w").write(SNIPPET)
    json.dump({"label": "tablenotes snippet for the 439 master table",
               "action_required": ("PASTE into the tablenotes block of "
                                   "modal_tcd_multiseed/phase4/table_439.tex and "
                                   "table_439_mdpi.tex -- this script does not edit them"),
               "targets": ["modal_tcd_multiseed/phase4/table_439.tex",
                           "modal_tcd_multiseed/phase4/table_439_mdpi.tex"],
               "facts_asserted": {
                   "lace_seeds": [0, 1, 2],
                   "detectree2_seeds": [0], "sam3_seeds": [0],
                   "sd_convention": "ddof=1",
                   "mps_multiseed_readme_band_is_ddof0": True}},
              open(a.out.replace(".tex", "_meta.json"), "w"), indent=2)
    print(SNIPPET)
    print(f"-> {os.path.relpath(a.out, io.REPO)}   (paste it; nothing was edited)")


if __name__ == "__main__":
    main()
